debug = true

[database]
url = "postgresql://postgres:postgres@localhost:5432/moni"
connections = 20

[server]
host = "127.0.0.1"
port = 8080

[firebase_config]
key = "test"
url = "https://test.firebaseio.com"

[gemini_config]
api_key = "AIzaSyBKa7HfGpbey3M8FVfj6lk9-desCFMALFA"